name: build electron
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Build Environment"
        required: true
        default: "dev"
        type: string

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Electron 앱 빌드
      - name: Install dependencies and build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npm run build -- --mac

      # 인증서 설정
      - name: Decode and install Apple certificate
        run: |
          echo "$APPLE_CERTIFICATE" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      # 앱 서명
      - name: Sign the app
        run: |
          codesign --deep --force --verbose --sign "3rd Party Mac Developer Application: HyeJoo Jun (X57DM4D9CF)" "dist/mac/MyElectronApp.app"

      # 서명 확인
      - name: Verify signature
        run: |
          codesign --verify --deep --verbose "dist/mac/MyElectronApp.app"

      # 앱 공증 요청
      - name: Notarize the app
        run: |
          xcrun altool --notarize-app -f "dist/mac/MyElectronApp.zip" --primary-bundle-id "com.oxfordlearnersbookshelf.ods" -u "$APPLE_ID" -p "$APPLE_APP_PASSWORD"

      # 스테이플링
      - name: Staple the app
        run: |
          xcrun stapler staple "dist/mac/MyElectronApp.app"
